package modelo;


public enum TipoMensaje
{
    LOGIN, SUCCESSLOGIN, FAILLOGIN, UNKNOWN, TERMINATESERVER, LOADTABLES, LOADTABLESVISIBLE, LOADTABLESNONVISIBLE,
    SUCCESSLOAD, FAILLOAD, READBINNACLE, READAMOUNT, ORDER, READRECORDORDER, SETAMOUNT, LOADAMOUNT, ADDPRODUCT, EDITPRODUCT,
    DELETEPRODUCT, LOADPORCENTORDER, LOADPRODUCTNEVERORDER, LOADPRODUCTTOTEN, SETVISIBLEPRODUCT, SETNONVISIBLEPRODUCT
}